CREATE TABLE IF NOT EXISTS corp.customer (
      customer_id INTEGER NOT NULL,
      account_num char(20),
      lname VARCHAR,
      fname VARCHAR,
      mi VARCHAR,
      address1 VARCHAR,
      address2 VARCHAR,
      address3 VARCHAR,
      address4 VARCHAR,
      city VARCHAR,
      state_province VARCHAR,
      postal_code VARCHAR,
      country VARCHAR,
      customer_region_id INTEGER,
      phone1 VARCHAR,
      phone2 VARCHAR,
      birthdate DATE,
      marital_status char(1),
      yearly_income VARCHAR,
      gender char(1),
      total_children INTEGER,
      num_children_at_home INTEGER,
      education VARCHAR,
      date_accnt_opened DATE,
      member_card VARCHAR,
      occupation VARCHAR,
      houseowner BOOLEAN,
      num_cars_owned INTEGER,
      fullname VARCHAR,
      CONSTRAINT id_pk PRIMARY KEY (customer_id));


    