CREATE TABLE IF NOT EXISTS corp.store (
    store_id INTEGER NOT NULL, 
    store_type VARCHAR, 
    region_id INTEGER, 
    store_name VARCHAR, 
    store_number INTEGER, 
    store_street_address VARCHAR, 
    store_city VARCHAR, 
    store_state VARCHAR, 
    store_postal_code VARCHAR, 
    store_country VARCHAR, 
    store_manager VARCHAR, 
    store_phone VARCHAR, 
    store_fax VARCHAR, 
    first_opened_date DATE, 
    last_remodel_date DATE, 
    store_sqft INTEGER, 
    grocery_sqft INTEGER, 
    frozen_sqft INTEGER, 
    meat_sqft INTEGER, 
    coffee_bar BOOLEAN, 
    video_store BOOLEAN, 
    salad_bar BOOLEAN, 
    prepared_food BOOLEAN, 
    florist BOOLEAN,
    CONSTRAINT id_pk PRIMARY KEY (store_id));